### PR TITLE
Added LDA to SimServer

### PR DESCRIPTION
**Pull request by msalahi**
Added a few "if" statements in simserver.SimModel to work with 'lda' as your semantic method. It doesn't pass all of the unit tests, but I don't know if some of those are specifically meant to work with LSI or not. Let me know if you think this works!

### CODE REVIEW

**Comment by piskvorky** [comment]
Nice, but I extended and reworked that part recently -- it will be part of the next simserver release (probably next month). 

That's why I don't merge this pull request -- but it will be in simserver anyway :)

**Comment by msalahi** [comment]
Oh, great! Did it look like the fork I did should behave correctly (so I can proceed with it in the meantime before your next release)?

**Comment by piskvorky** [comment]
I don't think so -- the training corpus you feed to LDA needs to support `len` (or be multi-pass). The generator `corpus()` supports neither.

**Comment by msalahi** [comment]
ok cool. if that's the only problem, i'll just hack it with `list(corpus())`. will that suffice for til the next release?

**Comment by piskvorky** [comment]
Yes, `list` should do it. Just be careful about the corpus size in RAM then :)

**Comment by msalahi** [comment]
yeah, it's only a temporary fix and memory shouldn't be a big problem just yet. 

in the unit tests, i replaced all instances of 'lsi' with 'lda' and tried to run it. is it a problem that "test_query_id", "test_query_document", and "test remote server incremental indexing" all fail...? or are those tests hardcoded to assume 'lsi' was the method chosen? here are the specific messages:

# 

## FAIL: test remote server incremental indexing

Traceback (most recent call last):
  File "test_simserver.py", line 134, in test_index
    self.check_equal(expected, got)
  File "test_simserver.py", line 80, in check_equal
    self.assertTrue(numpy.allclose(sims1.get(docid, 0.0), sims2.get(docid, 0.0), atol=1e-7))
AssertionError

# 

## FAIL: test_query_document (**main**.SessionServerTester)

Traceback (most recent call last):
  File "test_simserver.py", line 215, in test_query_document
    self.check_equal(expected, got)
  File "test_simserver.py", line 80, in check_equal
    self.assertTrue(numpy.allclose(sims1.get(docid, 0.0), sims2.get(docid, 0.0), atol=1e-7))
AssertionError

# 

## FAIL: test_query_id (**main**.SessionServerTester)

Traceback (most recent call last):
  File "test_simserver.py", line 191, in test_query_id
    self.check_equal(expected, got)
  File "test_simserver.py", line 80, in check_equal
    self.assertTrue(numpy.allclose(sims1.get(docid, 0.0), sims2.get(docid, 0.0), atol=1e-7))
AssertionError

---

**Comment by piskvorky** [comment]
Correct. You can leave the default at 'lsi' and pass `method='lda'` manually for training.

**Comment by msalahi** [comment]
Great, thanks a lot! If you want any help on the next release let me know!

**Pull request closed without merging**
